# Generated by Django 4.0.3 on 2022-03-07 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('code', models.CharField(max_length=20, verbose_name='Phrase opening code. Up to 20 characters')),
                ('phrase', models.TextField(verbose_name='Phrase')),
                ('secret_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TTL', models.PositiveIntegerField(default=3600, verbose_name='Time phrase life')),
            ],
        ),
    ]
